targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/models/**.dart
            - lib/providers/states/**.dart
            - lib/services/networking/**.dart
            - lib/enums/**.dart