ignore:
  - '**/*.gr.dart'
  - '**/*.g.dart'
  - '**/*.freezed.dart'
  - "**/*.mocks.dart"
  - '**/app_colors.dart'
  - '**/app_assets.dart'
  - '**/app_constants.dart'
  - '**/app_fonts.dart'
  - '**/app_themes.dart'
  - '**/routes.dart'
  - '**/typedefs.dart'
  - '/android/'
  - '/ios/'
  - '/build/'