---
name: preloved
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  clock: ^1.1.0
  time: ^2.0.0
  freezed_annotation: ^0.14.3
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.8
  flutter_secure_storage: ^4.2.1
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  build_runner: null
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/
